version: "3"

services:
  influxdb:
    image: influxdb:latest
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - ./data/grafana:/var/lib/influxdb

  grafana:
    image: grafana/grafana:5.0.4
    ports:
      - "8085:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    depends_on:
      - influxdb